module.exports = [
    {//default
        type: "AMRAP",
        location: "home",
        duration: "30",
        then: ["workouts/backgrounds", "workouts/30 min home 20 min AMRAP", "workouts/filter", "workouts/foreground elements"],
    },
    {
        type: "AMRAP",
        location: "home",
        duration: "5",
        then: ["workouts/backgrounds", "workouts/5 min home 3 min AMRAP", "workouts/filter", "workouts/foreground elements"],
    },
    {
        type: "AMRAP",
        location: "home",
        duration: "10",
        then: ["workouts/backgrounds", "workouts/10 min home 7 min AMRAP", "workouts/filter", "workouts/foreground elements"],
    },
    {
        type: "AMRAP",
        location: "home",
        duration: "15",
        then: ["workouts/backgrounds", "workouts/15 min home 10 min AMRAP", "workouts/filter", "workouts/foreground elements"],
    },
    {
        type: "AMRAP",
        location: "home",
        duration: "20",
        then: ["workouts/backgrounds", "workouts/20 min home 13 min AMRAP", "workouts/filter", "workouts/foreground elements"],
    },
    {
        type: "AMRAP",
        location: "home",
        duration: "25",
        then: ["workouts/backgrounds", "workouts/25 min home 15 min AMRAP", "workouts/filter", "workouts/foreground elements"],
    },
    {
        type: "AMRAP",
        location: "home",
        duration: "35",
        then: ["workouts/backgrounds", "workouts/35 min home 25 min AMRAP", "workouts/filter", "workouts/foreground elements"],
    },
    {
        type: "AMRAP",
        location: "home",
        duration: "40",
        then: ["workouts/backgrounds", "workouts/40 min home 30 min AMRAP", "workouts/filter", "workouts/foreground elements"],
    },
    {
        type: "AMRAP",
        location: "home",
        duration: "45",
        then: ["workouts/backgrounds", "workouts/45 min home 30 min AMRAP", "workouts/filter", "workouts/foreground elements"],
    },
    {
        type: "AMRAP",
        location: "home",
        duration: "50",
        then: ["workouts/backgrounds", "workouts/50 min home 30 min AMRAP", "workouts/filter", "workouts/foreground elements"],
    },
    {
        type: "AMRAP",
        location: "home",
        duration: "55",
        then: ["workouts/backgrounds", "workouts/55 min home 30 min AMRAP", "workouts/filter", "workouts/foreground elements"],
    },
    {
        type: "AMRAP",
        location: "home",
        duration: "60",
        then: ["workouts/backgrounds", "workouts/60 min home 30 min AMRAP", "workouts/filter", "workouts/foreground elements"],
    },
    {
        type: "AMRAP",
        location: "outdoor",
        duration: "5",
        then: ["workouts/backgrounds", "workouts/outdoor/5 min outdoor 3 min AMRAP", "workouts/filter", "workouts/foreground elements"],
    },
    {
        type: "AMRAP",
        location: "outdoor",
        duration: "10",
        then: ["workouts/backgrounds", "workouts/outdoor/10 min outdoor 7 min AMRAP", "workouts/filter", "workouts/foreground elements"],
    },
    {
        type: "AMRAP",
        location: "outdoor",
        duration: "15",
        then: ["workouts/backgrounds", "workouts/outdoor/15 min outdoor 10 min AMRAP", "workouts/filter", "workouts/foreground elements"],
    },
    {
        type: "AMRAP",
        location: "outdoor",
        duration: "20",
        then: ["workouts/backgrounds", "workouts/outdoor/20 min outdoor 13 min AMRAP", "workouts/filter", "workouts/foreground elements"],
    },
    {
        type: "AMRAP",
        location: "outdoor",
        duration: "25",
        then: ["workouts/backgrounds", "workouts/outdoor/25 min outdoor 15 min AMRAP", "workouts/filter", "workouts/foreground elements"],
    },
    {
        type: "AMRAP",
        location: "outdoor",
        duration: "30",
        then: ["workouts/backgrounds", "workouts/outdoor/30 min outdoor 20 min AMRAP", "workouts/filter", "workouts/foreground elements"],
    },
    {
        type: "AMRAP",
        location: "outdoor",
        duration: "35",
        then: ["workouts/backgrounds", "workouts/outdoor/35 min outdoor 25 min AMRAP", "workouts/filter", "workouts/foreground elements"],
    },
    {
        type: "AMRAP",
        location: "outdoor",
        duration: "40",
        then: ["workouts/backgrounds", "workouts/outdoor/40 min outdoor 30 min AMRAP", "workouts/filter", "workouts/foreground elements"],
    },
    {
        type: "AMRAP",
        location: "outdoor",
        duration: "45",
        then: ["workouts/backgrounds", "workouts/outdoor/45 min outdoor 30 min AMRAP", "workouts/filter", "workouts/foreground elements"],
    },
    {
        type: "AMRAP",
        location: "outdoor",
        duration: "50",
        then: ["workouts/backgrounds", "workouts/outdoor/50 min outdoor 30 min AMRAP", "workouts/filter", "workouts/foreground elements"],
    },
    {
        type: "AMRAP",
        location: "outdoor",
        duration: "55",
        then: ["workouts/backgrounds", "workouts/outdoor/55 min outdoor 30 min AMRAP", "workouts/filter", "workouts/foreground elements"],
    },
    {
        type: "AMRAP",
        location: "outdoor",
        duration: "60",
        then: ["workouts/backgrounds", "workouts/outdoor/60 min outdoor 30 min AMRAP", "workouts/filter", "workouts/foreground elements"],
    },
    {
        type: "AMRAP",
        location: "gym",
        duration: "5",
        then: ["workouts/backgrounds", "workouts/gym/5 min gym 3 min AMRAP", "workouts/filter", "workouts/foreground elements"],
    },
    {
        type: "AMRAP",
        location: "gym",
        duration: "10",
        then: ["workouts/backgrounds", "workouts/gym/10 min gym 7 min AMRAP", "workouts/filter", "workouts/foreground elements"],
    },
    {
        type: "AMRAP",
        location: "gym",
        duration: "15",
        then: ["workouts/backgrounds", "workouts/gym/15 min gym 10 min AMRAP", "workouts/filter", "workouts/foreground elements"],
    },
    {
        type: "AMRAP",
        location: "gym",
        duration: "20",
        then: ["workouts/backgrounds", "workouts/gym/20 min gym 13 min AMRAP", "workouts/filter", "workouts/foreground elements"],
    },
    {
        type: "AMRAP",
        location: "gym",
        duration: "25",
        then: ["workouts/backgrounds", "workouts/gym/25 min gym 15 min AMRAP", "workouts/filter", "workouts/foreground elements"],
    },
    {
        type: "AMRAP",
        location: "gym",
        duration: "30",
        then: ["workouts/backgrounds", "workouts/gym/30 min gym 20 min AMRAP", "workouts/filter", "workouts/foreground elements"],
    },
    {
        type: "AMRAP",
        location: "gym",
        duration: "35",
        then: ["workouts/backgrounds", "workouts/gym/35 min gym 25 min AMRAP", "workouts/filter", "workouts/foreground elements"],
    },
    {
        type: "AMRAP",
        location: "gym",
        duration: "40",
        then: ["workouts/backgrounds", "workouts/gym/40 min gym 30 min AMRAP", "workouts/filter", "workouts/foreground elements"],
    },
    {
        type: "AMRAP",
        location: "gym",
        duration: "45",
        then: ["workouts/backgrounds", "workouts/gym/45 min gym 30 min AMRAP", "workouts/filter", "workouts/foreground elements"],
    },
    {
        type: "AMRAP",
        location: "gym",
        duration: "50",
        then: ["workouts/backgrounds", "workouts/gym/50 min gym 30 min AMRAP", "workouts/filter", "workouts/foreground elements"],
    },
    {
        type: "AMRAP",
        location: "gym",
        duration: "55",
        then: ["workouts/backgrounds", "workouts/gym/55 min gym 30 min AMRAP", "workouts/filter", "workouts/foreground elements"],
    },
    {
        type: "AMRAP",
        location: "gym",
        duration: "60",
        then: ["workouts/backgrounds", "workouts/gym/60 min gym 30 min AMRAP", "workouts/filter", "workouts/foreground elements"],
    },
    {
        type: "WYN",
        location: "home",
        duration: "5",
        then: [],
    },
    {
        type: "WYN",
        location: "home",
        duration: "10",
        then: [],
    },
    {
        type: "WYN",
        location: "home",
        duration: "15",
        then: [],
    },
    {
        type: "WYN",
        location: "home",
        duration: "20",
        then: [],
    },
    {
        type: "WYN",
        location: "home",
        duration: "25",
        then: [],
    },
    {
        type: "WYN",
        location: "home",
        duration: "30",
        then: [],
    },
    {
        type: "WYN",
        location: "home",
        duration: "35",
        then: [],
    },
    {
        type: "WYN",
        location: "home",
        duration: "40",
        then: [],
    },
    {
        type: "WYN",
        location: "home",
        duration: "45",
        then: [],
    },
    {
        type: "WYN",
        location: "home",
        duration: "50",
        then: [],
    },
    {
        type: "WYN",
        location: "home",
        duration: "55",
        then: [],
    },
    {
        type: "WYN",
        location: "home",
        duration: "60",
        then: [],
    },
    {
        type: "WYN",
        location: "outdoor",
        duration: "5",
        then: [],
    },
   {
       type: "WYN",
       location: "outdoor",
       duration: "10",
        then: [],
    },
    {
        type: "WYN",
        location: "outdoor",
        duration: "15",
        then: [],
    },
    {
        type: "WYN",
        location: "outdoor",
        duration: "20",
        then: [],
    },
    {
        type: "WYN",
        location: "outdoor",
        duration: "25",
        then: [],
    },
    {
        type: "WYN",
        location: "outdoor",
        duration: "30",
        then: [],
    },
    {
        type: "WYN",
        location: "outdoor",
        duration: "35",
        then: [],
    },
    {
        type: "WYN",
        location: "outdoor",
        duration: "40",
        then: [],
    },
    {
        type: "WYN",
        location: "outdoor",
        duration: "45",
        then: [],
    },
    {
        type: "WYN",
        location: "outdoor",
        duration: "50",
        then: [],
    },
    {
        type: "WYN",
        location: "outdoor",
        duration: "55",
        then: [],
    },
    {
        type: "WYN",
        location: "outdoor",
        duration: "60",
        then: [],
    },
];
